blank_issues_enabled: false
contact_links:
  - name: Product Feature Request
    url: https://feedback.strapi.io/feature-requests
    about: Provide feedback to the Strapi team and ask for new features or enhancements!
  - name: Documentation Bug Report
    url: https://github.com/strapi/documentation/issues/new?template=BUG_REPORT.md&title%5B%5D=BUG
    about: Create a report to help us improve the Strapi documentation.
  - name: Documentation Request
    url: https://feedback.strapi.io/documentation
    about: Suggest a new part of the documentation we are missing!
  - name: Strapi Questions and Discussions
    url: https://forum.strapi.io
    about: Please ask and answer questions on the community forums.
  - name: Join the Community Discord
    url: https://discord.strapi.io
    about: Come and chat with other community members!
