name: 'Run E2E tests'
description: 'Run end to end tests'
inputs:
  dbOptions:
    description: 'Database options'
    required: true
  runEE:
    description: 'Should run EE or CE tests'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      env:
        DB_OPTIONS: ${{ inputs.dbOptions }}
        RUN_EE: ${{ inputs.runEE }}
      shell: bash
